### PR TITLE
Drop v0.3 support

### PR DESCRIPTION
**Pull request by ranjanan**
This PR drops v0.3 support.

### CODE REVIEW

**Comment by ranjanan** [comment]
@andrewcooke If this looks okay to you, we can modify the METADATA PR and tag the new release. I just wanted to bump this PR. Thank you!

**Comment by andrewcooke** [comment]
would you like commit rights to this project?  i work on julia so little now that just routine tasks like this take forever because i need to re-learn everything.

**Comment by andrewcooke** [comment]
i created https://github.com/JuliaLang/METADATA.jl/compare/metadata-v2...andrewcooke:pull-request/2e9bdd7b but it still has the 1.1.2.  if i:delete that from my METADATA repo using git gm then i get errors in julia:

```
julia> Pkg.publish()
ERROR: SystemError: opening file METADATA/CRC/versions/1.1.2/sha1: No such file or directory
 in open at ./iostream.jl:90
 in open at iostream.jl:112
 in publish at pkg/entry.jl:358
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61
```

**Comment by andrewcooke** [comment]
tried deleting METADATA and running Pkg.update() but that looks like it's buggered everything locally.  i'll come back to this later.

**Comment by ranjanan** [comment]
@andrewcooke If you could give me commit rights, I can tag and send a PR to METADATA on your behalf. Thanks!

**Pull request merged**
